name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        scala: [2.13.8]
        java: [adopt@1.8]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: coursier/cache-action@v6
      - uses: olafurpg/setup-scala@v13
      - name: Build
        run: sbt ++${{matrix.scalaVersion}} fullOptJS/webpack

      - name: Push to github-pages repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'webapp/target/scala-2.13/scalajs-bundler/main/dist'
          target-directory: 'static/codingame/marslander'
          destination-github-username: 'FloWi'
          destination-repository-name: 'content-flowi.github.io'
          user-email: 'github@flwi.de'
          target-branch: 'main'
